version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: renner-container
    environment:
      - MONGO_INITDB_DATABASE=renner
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config: